server:
  port: 8090
  
fraud.service: 
    protocol: http
    servicename: localhost
    port: 8080
    
--- 
spring:
    profiles: default
fraud.service: 
    protocol: http
    servicename: localhost
    port: 8080
---
spring:
    profiles: docker
fraud.service:
    protocol: http
    servicename: fraud-detection-service
    port: 8080
  
  